services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    # ports:
    #   - 8090:8090 # Nexus Web UI (uncomment after running web-gui.sh)
    #   - 9091:9091 # xmwebui (unused)
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on

      # ↓↓↓ Set these in your .env file ↓↓↓
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      # ↑↑↑ Set these in your .env file ↑↑↑

      - TZ=America/New_York
    volumes:
      - ./gluetun:/gluetun
      - ./forwarded-port:/tmp/gluetun
    restart: unless-stopped

  biglybt:
    build: .
    container_name: biglybt
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./forwarded-port:/tmp/gluetun
    restart: unless-stopped
